package lv.reinis.tinyledger.converter;

import static org.assertj.core.api.Assertions.assertThat;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

import org.junit.jupiter.api.Test;
import org.springframework.test.util.ReflectionTestUtils;

import lv.reinis.tinyledger.domain.Account;
import lv.reinis.tinyledger.domain.Customer;
import lv.reinis.tinyledger.domain.Transaction;
import lv.reinis.tinyledger.domain.TransactionType;
import lv.reinis.tinyledger.dto.AccountDto;
import lv.reinis.tinyledger.dto.AccountSummaryDto;
import lv.reinis.tinyledger.dto.CustomerAccountsDto;
import lv.reinis.tinyledger.dto.CustomerDto;
import lv.reinis.tinyledger.dto.TransactionDto;


class ConverterTests
{

	private static final Instant CREATED_AT = Instant.parse("2026-10-06T10:00:00Z");

	@Test
	void customerIsConverted()
	{
		final Customer customer = customer();

		final CustomerDto dto = new CustomerConverter().convert(customer);

		assertThat(dto).isEqualTo(new CustomerDto(customer.getId(), "Anna", CREATED_AT));
	}

	@Test
	void accountIsConvertedWithBalanceInCurrencyScale()
	{
		final Account account = account("JPY", "1000.000");

		final AccountDto dto = new AccountConverter().convert(account);

		assertThat(dto).isEqualTo(
				new AccountDto(account.getId(), account.getCustomer().getId(), "JPY", new BigDecimal("1000"), CREATED_AT));
	}

	@Test
	void transactionIsConvertedWithAmountsInCurrencyScale()
	{
		final Account account = account("EUR", "100.500");
		final Transaction transaction = withIdAndCreatedAt(
				new Transaction(account, TransactionType.DEPOSIT, new BigDecimal("100.5"), new BigDecimal("100.500"), "salary"));

		final TransactionDto dto = new TransactionConverter().convert(transaction);

		assertThat(dto).isEqualTo(new TransactionDto(transaction.getId(), account.getId(), TransactionType.DEPOSIT,
				new BigDecimal("100.50"), new BigDecimal("100.50"), "salary", CREATED_AT));
	}

	@Test
	void customerIsConvertedWithAccounts()
	{
		final Customer customer = customer();
		final Account euro = account("EUR", "100.500");

		final CustomerAccountsDto dto = new CustomerAccountsConverter(new AccountSummaryConverter()).convert(customer, List.of(euro));

		assertThat(dto.id()).isEqualTo(customer.getId());
		assertThat(dto.name()).isEqualTo("Anna");
		assertThat(dto.createdAt()).isEqualTo(CREATED_AT);
		assertThat(dto.accounts())
				.containsExactly(new AccountSummaryDto(euro.getId(), "EUR", new BigDecimal("100.50"), CREATED_AT));
	}

	@Test
	void convertAllKeepsOrder()
	{
		final Account euro = account("EUR", "1");
		final Account yen = account("JPY", "2");

		final List<AccountDto> dtos = new AccountConverter().convertAll(List.of(yen, euro));

		assertThat(dtos).extracting(AccountDto::currency).containsExactly("JPY", "EUR");
	}

	private static Customer customer()
	{
		return withIdAndCreatedAt(new Customer("Anna"));
	}

	private static Account account(final String currency, final String balance)
	{
		final Account account = withIdAndCreatedAt(new Account(customer(), currency));
		account.setBalance(new BigDecimal(balance));

		return account;
	}

	// Ids and timestamps are generated by Hibernate, so the entities expose no setters for them.
	private static <T> T withIdAndCreatedAt(final T entity)
	{
		ReflectionTestUtils.setField(entity, "id", UUID.randomUUID());
		ReflectionTestUtils.setField(entity, "createdAt", CREATED_AT);

		return entity;
	}

}
